[profile.release-with-debug]
inherits = "release"
debug = true

[package]
name = "rtpmidi"
version = "0.1.0"
edition = "2024"

[dependencies]
colog = "1.3.0"
log = "0.4.27"
tokio = { version = "1", features = ["full"] }
env_logger = "0.10"
mdns-sd = "0.13.9"
hostname = "0.4.1"
local-ip-address = "0.6.5"
